# Generated by Django 4.0.1 on 2022-01-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='valid school name', max_length=20)),
                ('no_of_students', models.IntegerField(help_text='number of students')),
                ('location', models.CharField(help_text='school locations', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='please enter first name', max_length=20)),
                ('last_name', models.CharField(help_text='please enter last name', max_length=20)),
                ('student_id', models.ForeignKey(help_text='student id belongs to school', on_delete=django.db.models.deletion.CASCADE, to='coresite.school')),
            ],
        ),
    ]
